last test

diff --git a/.github/workflows/run-tests-on-release.yml b/.github/workflows/run-tests-on-release.yml
--- a/.github/workflows/run-tests-on-release.yml
+++ b/.github/workflows/run-tests-on-release.yml
@@ -28,7 +28,7 @@ on:
         required: true
       SLACK_QA_STATUSES_WEBHOOK_URL:
         required: true
-
+        
 jobs:
   add-check-and-prepare-instance:
     runs-on: ubuntu-latest
@@ -46,14 +46,32 @@ jobs:
       BACKUP_VER: ${{ steps.cloud_variables.outputs.BACKUP_VER }}
       BACKUP_NAME: ${{ steps.cloud_variables.outputs.BACKUP_NAME }}
       CHECK_ID: ${{ steps.create-check.outputs.CHECK_ID }}
+      FRAMEWORK: ${{ steps.check-framework.TEST_FRAMEWORK }}
     steps:
       - uses: actions/checkout@v4
 
+      - id: check-framework
+        name: check if run playwright or cypress
+        env: 
+          VERSION: ${{inputs.VERSION}}
+        run: |
+          if (( ${VERSION//./} >= 319 )); then
+            echo "TEST_FRAMEWORK=playwright" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+          if (( ${VERSION//./} < 319 )); then
+            echo "TEST_FRAMEWORK=cypress" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+          echo "Could not determinate if run cypress or playwright" >&2
+          exit 1
+
       - name: Create check if release PR exists
+        if: ${{ steps.check-framework.TEST_FRAMEWORK }} == playwright
         id: create-check
         uses: ./.github/actions/checks/create-pull-request-check
         with:
-          PR_HEAD: "Test-add-tests-check-to-release-PR"
+          PR_HEAD: "Test-add-tests-check-to-release-PR" # TODO: change name before merging!!!
           CHECK_NAME: "Automation_tests_run"
           STATUS: "in_progress"
           TITLE: "Automation tests run"
@@ -80,15 +98,38 @@ jobs:
           BACKUP_ID: ${{ steps.cloud_variables.outputs.BACKUP_ID }}
 
       - uses: ./.github/actions/testmo/testmo-init
+        if: ${{ steps.check-framework.TEST_FRAMEWORK }} == playwright
         with:
           testmoUrl: ${{ secrets.TESTMO_URL }}
           testmoToken: ${{ secrets.TESTMO_TOKEN }}
           testmoRunName: "Playwright run ${{ env.CUSTOM_VERSION }}"
         id: init-testmo
 
-  run-tests:
+  run-cy-tests:
     runs-on: ubuntu-22.04
     needs: "add-check-and-prepare-instance"
+    if: ${{ needs.add-check-and-prepare-instance.outputs.TEST_FRAMEWORK }} == cypress
+    steps:
+      - name: Trigger dashboard cypress automation tests
+        run: |
+          export GITHUB_TOKEN=$( \
+            curl --request GET --url ${{ secrets.VAULT_URL}} --header "Authorization: JWT ${{ secrets.VAULT_JWT }}" | jq -r .token \
+          )
+
+          gh api /repos/saleor/saleor-dashboard/dispatches \
+            --input - <<< '{
+              "event_type": "automation-tests-event",
+              "client_payload": {
+                "project": "DASHBOARD",
+                "environment": "SANDBOX",
+                "version": "${{ needs.add-check-and-prepare-instance.outputs.VERSION }}",
+              }
+            }'
+
+  run-pw-tests:
+    runs-on: ubuntu-22.04
+    needs: "add-check-and-prepare-instance"
+    if: ${{ needs.add-check-and-prepare-instance.outputs.TEST_FRAMEWORK }} == playwright
     strategy:
       fail-fast: false
       matrix:
@@ -120,9 +161,9 @@ jobs:
           testmoToken: ${{ secrets.TESTMO_TOKEN }}
           testmoRunId: ${{ needs.add-check-and-prepare-instance.outputs.TESTMO_RUN_ID }}
 
-  tests-complete:
-    if: '!cancelled()'
-    needs: ["add-check-and-prepare-instance", "run-tests"]
+  tests-complete-pw:
+    if: ${{ !cancelled() && needs.add-check-and-prepare-instance.outputs.TEST_FRAMEWORK  == playwright }}
+    needs: ["add-check-and-prepare-instance", "run-pw-tests"]
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v4
@@ -171,10 +212,11 @@ jobs:
 
   update-check-status-if-previous-job-fails:
     runs-on: ubuntu-latest
-    needs: [tests-complete]
+    needs: [tests-complete-pw, add-check-and-prepare-instance]
     if: |
       always() &&
-      (needs.tests-complete != 'success' && cancelled())
+      (needs.tests-complete-pw != 'success' && cancelled()) &&
+      ${{ needs.add-check-and-prepare-instance.outputs.TEST_FRAMEWORK  }} == playwright
 
     steps:
       - uses: actions/checkout@v4
@@ -190,7 +232,7 @@ jobs:
           DETAILS_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
 
       - name: Change job status if previous job failed or skipped
-        if: needs.tests-complete != 'success' && !cancelled()
+        if: needs.tests-complete-pw != 'success' && !cancelled()
         uses: ./.github/actions/checks/update-pull-request-check
         with:
           CHECK_ID: ${{ needs.add-check-and-prepare-instance.outputs.CHECK_ID }}
